version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  web:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "myproject.wsgi:application"]

volumes:
  postgres_data:
