services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn yandex_dzen.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/yandex_dzen
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: