# Generated by Django 4.2.19 on 2025-03-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_comment_comment_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.FloatField(default=0, verbose_name='Average Rating'),
        ),
    ]
