# Generated by Django 4.2.19 on 2025-03-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='average_rating',
        ),
    ]
